import type { StarlightSidebarTopicsUserConfig } from 'starlight-sidebar-topics';

export const sidebarTopics: StarlightSidebarTopicsUserConfig = [
  {
    label: {
      da: 'Dokumenter',
      de: 'Dokumente',
      en: 'Docs',
      es: 'Documentos',
      fr: 'Documents',
      hi: 'दस्तावेज़',
      id: 'Dokumen',
      it: 'Documenti',
      ja: 'ドキュメント',
      ko: '문서',
      'pt-BR': 'Documentos',
      'pt-PT': 'Documentos',
      ru: 'Документы',
      tr: 'Belgeler',
      uk: 'Документи',
      'zh-CN': '文档',
    },
    link: 'docs',
    icon: 'open-book',
    items: [
      {
        label: 'Welcome to Aspire',
        translations: {
          da: 'Velkommen til Aspire',
          de: 'Willkommen bei Aspire',
          en: 'Welcome to Aspire',
          es: 'Bienvenido a Aspire',
          fr: 'Bienvenue à Aspire',
          hi: 'Aspire में आपका स्वागत है',
          id: 'Selamat datang di Aspire',
          it: 'Benvenuto in Aspire',
          ja: 'Aspire へようこそ',
          ko: 'Aspire에 오신 것을 환영합니다',
          'pt-BR': 'Bem-vindo ao Aspire',
          'pt-PT': 'Bem-vindo ao Aspire',
          ru: 'Добро пожаловать в Aspire',
          tr: "Aspire'a Hoş Geldiniz",
          uk: 'Ласкаво просимо до Aspire',
          'zh-CN': '欢迎使用 Aspire',
        },
        slug: 'docs',
      },
      {
        label: "What's new",
        collapsed: true,
        autogenerate: { directory: 'whats-new' },
        translations: {
          da: 'Hvad er nyt',
          de: 'Was gibt es Neues',
          en: "What's new",
          es: 'Novedades',
          fr: 'Quoi de neuf',
          hi: 'क्या नया है',
          id: 'Apa yang baru',
          it: 'Novità',
          ja: '新着情報',
          ko: '새로운 소식',
          'pt-BR': 'Novidades',
          'pt-PT': 'Novidades',
          ru: 'Что нового',
          tr: 'Yeni neler var',
          uk: 'Що нового',
          'zh-CN': '新内容',
        },
      },
      {
        label: 'Get started',
        translations: {
          da: 'Kom godt i gang',
          de: 'Erste schritte',
          en: 'Get started',
          es: 'Empezar',
          fr: 'Commencer',
          hi: 'शुरू करें',
          id: 'Mulai',
          it: 'Iniziare',
          ja: '始める',
          ko: '시작하기',
          'pt-BR': 'Começar',
          'pt-PT': 'Começar',
          ru: 'Начать',
          tr: 'Başlamak',
          uk: 'Розпочати',
          'zh-CN': '开始',
        },
        items: [
          {
            label: 'Prerequisites',
            translations: {
              da: 'Forudsætninger',
              de: 'Voraussetzungen',
              en: 'Prerequisites',
              es: 'Requisitos previos',
              fr: 'Prérequis',
              hi: 'पूर्वापेक्षाएँ',
              id: 'Prasyarat',
              it: 'Prerequisiti',
              ja: '前提条件',
              ko: '전제 조건',
              'pt-BR': 'Pré-requisitos',
              'pt-PT': 'Pré-requisitos',
              ru: 'Предварительные требования',
              tr: 'Ön koşullar',
              uk: 'Попередні вимоги',
              'zh-CN': '先决条件',
            },
            slug: 'get-started/prerequisites',
          },
          {
            label: 'Install CLI',
            translations: {
              da: 'Installer CLI',
              de: 'CLI installieren',
              en: 'Install CLI',
              es: 'Instalar CLI',
              fr: 'Installer CLI',
              hi: 'CLI इंस्टॉल करें',
              id: 'Instal CLI',
              it: 'Installa CLI',
              ja: 'CLI をインストール',
              ko: 'CLI 설치',
              'pt-BR': 'Instalar CLI',
              'pt-PT': 'Instalar CLI',
              ru: 'Установить CLI',
              tr: 'CLI Kur',
              uk: 'Встановити CLI',
              'zh-CN': '安装 CLI',
            },
            slug: 'get-started/install-cli',
          },
          {
            label: 'Build your first app',
            translations: {
              da: 'Byg din første app',
              de: 'Erstellen Sie Ihre erste App',
              en: 'Build your first app',
              es: 'Construye tu primera app',
              fr: 'Construisez votre première application',
              hi: 'अपना पहला ऐप बनाएं',
              id: 'Bangun aplikasi pertama Anda',
              it: 'Crea la tua prima app',
              ja: '最初のアプリを作成',
              ko: '첫 번째 앱 만들기',
              'pt-BR': 'Construa seu primeiro app',
              'pt-PT': 'Construa a sua primeira app',
              ru: 'Создайте свое первое приложение',
              tr: 'İlk uygulamanızı oluşturun',
              uk: 'Створіть свій перший додаток',
              'zh-CN': '构建您的第一个应用',
            },
            slug: 'get-started/first-app',
          },
          {
            label: 'Deploy your first app',
            translations: {
              da: 'Udrul din første app',
              de: 'Bereitstellung Ihrer ersten App',
              en: 'Deploy your first app',
              es: 'Despliega tu primera app',
              fr: 'Déployez votre première application',
              hi: 'अपना पहला ऐप तैनात करें',
              id: 'Deploy aplikasi pertama Anda',
              it: 'Distribuisci la tua prima app',
              ja: '最初のアプリをデプロイ',
              ko: '첫 번째 앱 배포',
              'pt-BR': 'Implante seu primeiro app',
              'pt-PT': 'Implemente a sua primeira app',
              ru: 'Разверните свое первое приложение',
              tr: 'İlk uygulamanızı dağıtın',
              uk: 'Розгорніть свій перший додаток',
              'zh-CN': '部署您的第一个应用',
            },
            slug: 'get-started/deploy-first-app',
          },
          {
            label: 'Aspireify an existing app',
            translations: {
              da: 'Aspireify en eksisterende app',
              de: 'Eine bestehende App Aspireify',
              en: 'Aspireify an existing app',
              es: 'Aspireify una aplicación existente',
              fr: 'Aspireify une application existante',
              hi: 'मौजूदा ऐप को Aspireify करें',
              id: 'Aspireify aplikasi yang sudah ada',
              it: "Aspireify un'app esistente",
              ja: '既存のアプリを Aspireify する',
              ko: '기존 앱을 Aspireify하기',
              'pt-BR': 'Aspireify um app existente',
              'pt-PT': 'Aspireify uma app existente',
              ru: 'Aspireify существующее приложение',
              tr: 'Mevcut bir uygulamayı Aspireify et',
              uk: 'Aspireify наявний застосунок',
              'zh-CN': '对现有应用进行 Aspireify',
            },
            slug: 'get-started/add-aspire-existing-app',
          },
        ],
      },
      {
        label: 'Fundamentals',
        collapsed: true,
        translations: {
          da: 'Begreber',
          de: 'Grundlagen',
          en: 'Fundamentals',
          es: 'Fundamentos',
          fr: 'Notions fondamentales',
          hi: 'मूल बातें',
          id: 'Dasar-dasar',
          it: 'Fondamenti',
          ja: '基本',
          ko: '기본 사항',
          'pt-BR': 'Fundamentos',
          'pt-PT': 'Fundamentos',
          ru: 'Основы',
          tr: 'Temeller',
          uk: 'Основи',
          'zh-CN': '基础知识',
        },
        items: [
          {
            label: 'What is Aspire?',
            translations: {
              da: 'Hvad er Aspire?',
              de: 'Was ist Aspire?',
              en: 'What is Aspire?',
              es: '¿Qué es Aspire?',
              fr: 'Qu’est-ce qu’Aspire ?',
              hi: 'Aspire क्या है?',
              id: 'Apa itu Aspire?',
              it: 'Che cos’è Aspire?',
              ja: 'Aspire とは何ですか?',
              ko: 'Aspire란 무엇인가요?',
              'pt-BR': 'O que é Aspire?',
              'pt-PT': 'O que é Aspire?',
              ru: 'Что такое Aspire?',
              tr: 'Aspire nedir?',
              uk: 'Що таке Aspire?',
              'zh-CN': 'Aspire 是什么？',
            },
            slug: 'get-started/what-is-aspire',
          },
          {
            label: 'What is the AppHost?',
            translations: {
              da: 'Hvad er AppHost?',
              de: 'Was ist der AppHost?',
              en: 'What is the AppHost?',
              es: '¿Qué es el AppHost?',
              fr: "Qu'est-ce que l’AppHost ?",
              hi: 'AppHost क्या है?',
              id: 'Apa itu AppHost?',
              it: "Che cos'è l’AppHost?",
              ja: 'AppHost とは?',
              ko: 'AppHost란 무엇인가요?',
              'pt-BR': 'O que é o AppHost?',
              'pt-PT': 'O que é o AppHost?',
              ru: 'Что такое AppHost?',
              tr: 'AppHost nedir?',
              uk: 'Що таке AppHost?',
              'zh-CN': '什么是 AppHost？',
            },
            slug: 'get-started/app-host',
          },
          {
            label: 'Understanding resources',
            translations: {
              da: 'Forstå ressourcer',
              de: 'Ressourcen verstehen',
              en: 'Understanding resources',
              es: 'Comprender los recursos',
              fr: 'Comprendre les ressources',
              hi: 'संसाधनों को समझना',
              id: 'Memahami Sumber Daya',
              it: 'Comprendere le risorse',
              ja: 'リソースの理解',
              ko: '리소스 이해',
              'pt-BR': 'Compreendendo os recursos',
              'pt-PT': 'Compreender os recursos',
              ru: 'Понимание ресурсов',
              tr: 'Kaynakları anlama',
              uk: 'Розуміння ресурсів',
              'zh-CN': '了解资源',
            },
            slug: 'get-started/resources',
          },
          {
            label: 'Pipelines and app topology',
            translations: {
              da: 'Udrulning og apptopologi',
              de: 'Bereitstellung und App-Topologie',
              en: 'Pipelines and app topology',
              es: 'Despliegue y topología de la aplicación',
              fr: 'Déploiement et topologie de l’application',
              hi: 'परिनियोजन और ऐप टोपोलॉजी',
              id: 'Penyebaran dan topologi aplikasi',
              it: 'Distribuzione e topologia dell’applicazione',
              ja: 'デプロイとアプリのトポロジ',
              ko: '배포 및 앱 토폴로지',
              'pt-BR': 'Implantação e topologia do aplicativo',
              'pt-PT': 'Implementação e topologia da aplicação',
              ru: 'Развертывание и топология приложения',
              tr: 'Dağıtım ve uygulama topolojisi',
              uk: 'Розгортання і топологія застосунку',
              'zh-CN': '部署与应用拓扑',
            },
            slug: 'get-started/pipelines',
          },
          {
            label: 'Service discovery',
            translations: {
              da: 'Tjenesteopdagelse',
              de: 'Dienstermittlung',
              en: 'Service discovery',
              es: 'Descubrimiento de servicios',
              fr: 'Découverte de services',
              hi: 'सेवा खोज',
              id: 'Penemuan layanan',
              it: 'Individuazione del servizio',
              ja: 'サービス検出',
              ko: '서비스 검색',
              'pt-BR': 'Descoberta de serviços',
              'pt-PT': 'Descoberta de serviços',
              ru: 'Обнаружение служб',
              tr: 'Hizmet keşfi',
              uk: 'Виявлення служб',
              'zh-CN': '服务发现',
            },
            slug: 'fundamentals/service-discovery',
          },
          {
            label: 'Service defaults',
            translations: {
              da: 'Tjenestestandarder',
              de: 'Dienst-Standardeinstellungen',
              en: 'Service defaults',
              es: 'Valores predeterminados del servicio',
              fr: 'Paramètres par défaut du service',
              hi: 'सेवा डिफ़ॉल्ट',
              id: 'Default layanan',
              it: 'Impostazioni predefinite del servizio',
              ja: 'サービスの既定値',
              ko: '서비스 기본값',
              'pt-BR': 'Padrões de serviço',
              'pt-PT': 'Padrões de serviço',
              ru: 'Значения по умолчанию для служб',
              tr: 'Hizmet varsayılanları',
              uk: 'Значення за замовчуванням служби',
              'zh-CN': '服务默认值',
            },
            slug: 'fundamentals/service-defaults',
          },
          {
            label: 'Launch profiles',
            translations: {
              da: 'Start profiler',
              de: 'Startprofile',
              en: 'Launch profiles',
              es: 'Perfiles de inicio',
              fr: 'Profils de lancement',
              hi: 'लॉन्च प्रोफ़ाइल',
              id: 'Profil peluncuran',
              it: 'Profili di avvio',
              ja: '起動プロファイル',
              ko: '시작 프로필',
              'pt-BR': 'Perfis de inicialização',
              'pt-PT': 'Perfis de inicialização',
              ru: 'Профили запуска',
              tr: 'Başlatma profilleri',
              uk: 'Профілі запуску',
              'zh-CN': '启动配置文件',
            },
            slug: 'fundamentals/launch-profiles',
          },
          {
            label: 'Health checks',
            translations: {
              da: 'Sundhedstjek',
              de: 'Integritätsprüfungen',
              en: 'Health checks',
              es: 'Comprobaciones de estado',
              fr: "Vérifications de l'état",
              hi: 'स्वास्थ्य जांच',
              id: 'Pemeriksaan kesehatan',
              it: 'Controlli di integrità',
              ja: '正常性チェック',
              ko: '상태 확인',
              'pt-BR': 'Verificações de integridade',
              'pt-PT': 'Verificações de integridade',
              ru: 'Проверки работоспособности',
              tr: 'Durum denetimleri',
              uk: 'Перевірки справності',
              'zh-CN': '运行状况检查',
            },
            slug: 'fundamentals/health-checks',
          },
        ],
      },
      {
        label: 'Testing',
        collapsed: true,
        translations: {
          da: 'Test',
          de: 'Tests',
          en: 'Testing',
          es: 'Pruebas',
          fr: 'Tests',
          hi: 'परीक्षण',
          id: 'Pengujian',
          it: 'Test',
          ja: 'テスト',
          ko: '테스트',
          pt: 'Testes',
          'pt-BR': 'Testes',
          'pt-PT': 'Testes',
          ru: 'Тестирование',
          tr: 'Test',
          uk: 'Тестування',
          'zh-CN': '测试',
        },
        items: [
          {
            label: 'Overview',
            translations: {
              da: 'Oversigt',
              de: 'Übersicht',
              en: 'Overview',
              es: 'Descripción general',
              fr: "Vue d'ensemble",
              hi: 'अवलोकन',
              id: 'Ikhtisar',
              it: 'Panoramica',
              ja: '概要',
              ko: '개요',
              pt: 'Visão geral',
              'pt-BR': 'Visão geral',
              'pt-PT': 'Visão geral',
              ru: 'Обзор',
              tr: 'Genel Bakış',
              uk: 'Огляд',
              'zh-CN': '概述',
            },
            slug: 'testing/overview',
          },
          {
            label: 'Write your first test',
            translations: {
              da: 'Skriv din første test',
              de: 'Schreibe deinen ersten Test',
              en: 'Write your first test',
              es: 'Escribe tu primera prueba',
              fr: 'Écrivez votre premier test',
              hi: 'अपना पहला परीक्षण लिखें',
              id: 'Tulis tes pertama Anda',
              it: 'Scrivi il tuo primo test',
              ja: '最初のテストを書く',
              ko: '첫 번째 테스트 작성',
              pt: 'Escreva seu primeiro teste',
              'pt-BR': 'Escreva seu primeiro teste',
              'pt-PT': 'Escreva o seu primeiro teste',
              ru: 'Напишите свой первый тест',
              tr: 'İlk testinizi yazın',
              uk: 'Напишіть свій перший тест',
              'zh-CN': '编写您的第一个测试',
            },
            slug: 'testing/write-your-first-test',
          },
          {
            label: 'Manage the AppHost in tests',
            translations: {
              da: 'Administrer AppHost i tests',
              de: 'Verwalten Sie den AppHost in Tests',
              en: 'Manage the AppHost in tests',
              es: 'Administrar el AppHost en pruebas',
              fr: "Gérer l'AppHost dans les tests",
              hi: 'परीक्षणों में AppHost प्रबंधित करें',
              id: 'Kelola AppHost dalam tes',
              it: "Gestisci l'AppHost nei test",
              ja: 'テストで AppHost を管理する',
              ko: '테스트에서 AppHost 관리',
              pt: 'Gerenciar o AppHost em testes',
              'pt-BR': 'Gerenciar o AppHost em testes',
              'pt-PT': 'Gerir o AppHost em testes',
              ru: 'Управление AppHost в тестах',
              tr: "Testlerde AppHost'u yönetin",
              uk: 'Керування AppHost у тестах',
              'zh-CN': '在测试中管理 AppHost',
            },
            slug: 'testing/manage-app-host',
          },
          {
            label: 'Access resources in tests',
            translations: {
              da: 'Få adgang til ressourcer i tests',
              de: 'Zugriff auf Ressourcen in Tests',
              en: 'Access resources in tests',
              es: 'Acceder a recursos en pruebas',
              fr: 'Accéder aux ressources dans les tests',
              hi: 'परीक्षणों में संसाधनों तक पहुंचें',
              id: 'Akses sumber daya dalam tes',
              it: 'Accedi alle risorse nei test',
              ja: 'テストでリソースにアクセスする',
              ko: '테스트에서 리소스 액세스',
              pt: 'Acessar recursos em testes',
              'pt-BR': 'Acessar recursos em testes',
              'pt-PT': 'Aceder a recursos em testes',
              ru: 'Доступ к ресурсам в тестах',
              tr: 'Testlerde kaynaklara erişin',
              uk: 'Доступ до ресурсів у тестах',
              'zh-CN': '在测试中访问资源',
            },
            slug: 'testing/accessing-resources',
          },
        ],
      },
      {
        label: 'Architecture',
        translations: {
          da: 'Arkitektur',
          de: 'Architektur',
          en: 'Architecture',
          es: 'Arquitectura',
          fr: 'Architecture',
          hi: 'आर्किटेक्चर',
          id: 'Arsitektur',
          it: 'Architettura',
          ja: 'アーキテクチャ',
          ko: '아키텍처',
          'pt-BR': 'Arquitetura',
          'pt-PT': 'Arquitetura',
          ru: 'Архитектура',
          tr: 'Mimari',
          uk: 'Архітектура',
          'zh-CN': '架构',
        },
        collapsed: true,
        items: [
          {
            label: 'Overview',
            translations: {
              da: 'Oversigt',
              de: 'Übersicht',
              en: 'Overview',
              es: 'Descripción general',
              fr: "Vue d'ensemble",
              hi: 'अवलोकन',
              id: 'Ikhtisar',
              it: 'Panoramica',
              ja: '概要',
              ko: '개요',
              pt: 'Visão geral',
              'pt-BR': 'Visão geral',
              'pt-PT': 'Visão geral',
              ru: 'Обзор',
              tr: 'Genel Bakış',
              uk: 'Огляд',
              'zh-CN': '概述',
            },
            slug: 'architecture/overview',
          },
          {
            label: 'Resource model',
            translations: {
              da: 'Ressourcemodel',
              de: 'Ressourcenmodell',
              en: 'Resource model',
              es: 'Modelo de recurso',
              fr: 'Modèle de ressource',
              hi: 'संसाधन मॉडल',
              id: 'Model Sumber Daya',
              it: 'Modello di risorsa',
              ja: 'リソースモデル',
              ko: '리소스 모델',
              'pt-BR': 'Modelo de Recurso',
              'pt-PT': 'Modelo de Recurso',
              ru: 'Модель ресурса',
              tr: 'Kaynak Modeli',
              uk: 'Модель ресурсу',
              'zh-CN': '资源模型',
            },
            slug: 'architecture/resource-model',
          },
          {
            label: 'Resource hierarchies',
            translations: {
              da: 'Ressourcehierarkier',
              de: 'Ressourcenhierarchien',
              en: 'Resource hierarchies',
              es: 'Jerarquías de recursos',
              fr: 'Hiérarchies de ressources',
              hi: 'संसाधन पदानुक्रम',
              id: 'Hierarki Sumber Daya',
              it: 'Gerarchie delle risorse',
              ja: 'リソース階層',
              ko: '리소스 계층',
              'pt-BR': 'Hierarquias de Recursos',
              'pt-PT': 'Hierarquias de Recursos',
              ru: 'Иерархии ресурсов',
              tr: 'Kaynak Hiyerarşileri',
              uk: 'Ієрархії ресурсів',
              'zh-CN': '资源层次结构',
            },
            slug: 'architecture/resource-hierarchies',
          },
          {
            label: 'Resource API patterns',
            translations: {
              da: 'Ressource-API-mønstre',
              de: 'Ressource-API-Muster',
              en: 'Resource API patterns',
              es: 'Patrones de API de recursos',
              fr: "Modèles d'API de ressources",
              hi: 'संसाधन एपीआई पैटर्न',
              id: 'Pola API Sumber Daya',
              it: 'Modelli di API di risorse',
              ja: 'リソースAPIパターン',
              ko: '리소스 API 패턴',
              'pt-BR': 'Padrões de API de Recursos',
              'pt-PT': 'Padrões de API de Recursos',
              ru: 'Шаблоны API ресурсов',
              tr: 'Kaynak API Desenleri',
              uk: 'Шаблони API ресурсів',
              'zh-CN': '资源API模式',
            },
            slug: 'architecture/resource-api-patterns',
          },
          {
            label: 'Resource publishing',
            translations: {
              da: 'Ressourcepublicering',
              de: 'Ressourcenveröffentlichung',
              en: 'Resource publishing',
              es: 'Publicación de recursos',
              fr: 'Publication de ressources',
              hi: 'संसाधन प्रकाशन',
              id: 'Penerbitan Sumber Daya',
              it: 'Pubblicazione delle risorse',
              ja: 'リソースの公開',
              ko: '리소스 게시',
              'pt-BR': 'Publicação de Recursos',
              'pt-PT': 'Publicação de Recursos',
              ru: 'Публикация ресурсов',
              tr: 'Kaynak Yayınlama',
              uk: 'Публікація ресурсів',
              'zh-CN': '资源发布',
            },
            slug: 'architecture/resource-publishing',
          },
          {
            label: 'Resource examples',
            translations: {
              da: 'Ressourceeksempler',
              de: 'Ressourcenbeispiele',
              en: 'Resource examples',
              es: 'Ejemplos de recursos',
              fr: 'Exemples de ressources',
              hi: 'संसाधन उदाहरण',
              id: 'Contoh Sumber Daya',
              it: 'Esempi di risorse',
              ja: 'リソースの例',
              ko: '리소스 예제',
              'pt-BR': 'Exemplos de Recursos',
              'pt-PT': 'Exemplos de Recursos',
              ru: 'Примеры ресурсов',
              tr: 'Kaynak Örnekleri',
              uk: 'Приклади ресурсів',
              'zh-CN': '资源示例',
            },
            slug: 'architecture/resource-examples',
          },
          {
            label: 'Glossary',
            translations: {
              da: 'Ordbog',
              de: 'Glossar',
              en: 'Glossary',
              es: 'Glosario',
              fr: 'Glossaire',
              hi: 'शब्दावली',
              id: 'Kamus',
              it: 'Glossario',
              ja: '用語集',
              ko: '용어집',
              'pt-BR': 'Glossário',
              'pt-PT': 'Glossário',
              ru: 'Глоссарий',
              tr: 'Sözlük',
              uk: 'Глосарій',
              'zh-CN': '术语表',
            },
            slug: 'architecture/glossary',
          },
        ],
      },
    ],
  },
  {
    label: {
      en: 'Integrations',
      es: 'Integraciones',
      fr: 'Intégrations',
      de: 'Integrationen',
      it: 'Integrazioni',
      pt: 'Integrações',
      ru: 'Интеграции',
      'zh-CN': '集成',
      da: 'Integrationer',
      hi: 'इंटीग्रेशन',
      id: 'Integrasi',
      ja: 'インテグレーション',
      ko: '통합',
      'pt-BR': 'Integrações',
      'pt-PT': 'Integrações',
      tr: 'Entegrasyonlar',
      uk: 'Інтеграції',
    },
    link: '/integrations/gallery',
    icon: 'puzzle',
    items: [
      {
        label: 'Explore',
        translations: {
          da: 'Udforsk',
          de: 'Entdecken',
          en: 'Explore',
          es: 'Explorar',
          fr: 'Explorer',
          hi: 'अन्वेषण',
          id: 'Jelajahi',
          it: 'Esplora',
          ja: '参照',
          ko: '탐색',
          pt: 'Explorar',
          'pt-BR': 'Explorar',
          'pt-PT': 'Explorar',
          ru: 'Исследовать',
          tr: 'Keşfet',
          uk: 'Дослідити',
          'zh-CN': '探索',
        },
        items: [
          {
            label: 'Integration gallery',
            translations: {
              da: 'Integrationsgalleri',
              de: 'Integrationsgalerie',
              en: 'Integration gallery',
              es: 'Galería de integraciones',
              fr: 'Galerie d’intégrations',
              hi: 'इंटीग्रेशन गैलरी',
              id: 'Galeri integrasi',
              it: 'Galleria delle integrazioni',
              ja: 'インテグレーションギャラリー',
              ko: '통합 갤러리',
              pt: 'Galeria de integrações',
              'pt-BR': 'Galeria de integrações',
              'pt-PT': 'Galeria de integrações',
              ru: 'Галерея интеграций',
              tr: 'Entegrasyon galerisi',
              uk: 'Галерея інтеграцій',
              'zh-CN': '集成图库',
            },
            slug: 'integrations/gallery',
          },
          {
            label: 'Overview',
            translations: {
              da: 'Oversigt',
              de: 'Übersicht',
              en: 'Overview',
              es: 'Descripción general',
              fr: "Vue d'ensemble",
              hi: 'अवलोकन',
              id: 'Ikhtisar',
              it: 'Panoramica',
              ja: '概要',
              ko: '개요',
              pt: 'Visão geral',
              'pt-BR': 'Visão geral',
              'pt-PT': 'Visão geral',
              ru: 'Обзор',
              tr: 'Genel Bakış',
              uk: 'Огляд',
              'zh-CN': '概述',
            },
            slug: 'integrations/overview',
          },
        ],
      },
      {
        label: 'Artificial Intelligence (AI)',
        collapsed: true,
        translations: {
          da: 'Kunstig intelligens (AI)',
          de: 'Künstliche Intelligenz (KI)',
          en: 'Artificial Intelligence (AI)',
          es: 'Inteligencia Artificial (IA)',
          fr: 'Intelligence Artificielle (IA)',
          hi: 'कृत्रिम बुद्धिमत्ता (एआई)',
          id: 'Kecerdasan Buatan (AI)',
          it: 'Intelligenza Artificiale (IA)',
          ja: '人工知能 (AI)',
          ko: '인공지능 (AI)',
          pt: 'Inteligência Artificial (IA)',
          'pt-BR': 'Inteligência Artificial (IA)',
          'pt-PT': 'Inteligência Artificial (IA)',
          ru: 'Искусственный интеллект (ИИ)',
          tr: 'Yapay Zeka (YZ)',
          uk: 'Штучний інтелект (ШІ)',
          'zh-CN': '人工智能 (AI)',
        },
        items: [
          { label: 'GitHub Models', slug: 'integrations/ai/github-models' },
          { label: 'Ollama', slug: 'integrations/ai/ollama' },
          { label: 'OpenAI', slug: 'integrations/ai/openai' },
        ],
      },
      {
        label: 'Cloud providers',
        collapsed: true,
        translations: {
          da: 'Cloud-udbydere',
          de: 'Cloud-Anbieter',
          en: 'Cloud providers',
          es: 'Proveedores de la nube',
          fr: 'Fournisseurs de cloud',
          hi: 'क्लाउड प्रदाता',
          id: 'Penyedia Cloud',
          it: 'Provider Cloud',
          ja: 'クラウドプロバイダー',
          ko: '클라우드 제공업체',
          pt: 'Provedores de Nuvem',
          'pt-BR': 'Provedores de Nuvem',
          'pt-PT': 'Provedores de Nuvem',
          ru: 'Облачные провайдеры',
          tr: 'Bulut Sağlayıcıları',
          uk: 'Хмарні провайдери',
          'zh-CN': '云提供商',
        },
        items: [
          {
            label: 'AWS',
            link: 'https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/aspire-integrations.html',
          },
          {
            label: 'Azure',
            collapsed: true,
            items: [
              { label: 'Overview', slug: 'integrations/cloud/azure/overview' },
              {
                label: 'Customize Azure resources',
                slug: 'integrations/cloud/azure/customize-resources',
              },
              {
                label: 'Local Azure provisioning',
                slug: 'integrations/cloud/azure/local-provisioning',
              },
              {
                label: 'Configure Azure Container Apps',
                slug: 'integrations/cloud/azure/configure-container-apps',
              },
              {
                label: 'Azure AI',
                collapsed: true,
                items: [
                  {
                    label: 'AI compatibility matrix',
                    slug: 'integrations/cloud/azure/ai-compatibility-matrix',
                  },
                  {
                    label: 'Azure AI Foundry',
                    slug: 'integrations/cloud/azure/azure-ai-foundry',
                  },
                  {
                    label: 'Azure AI Inference',
                    slug: 'integrations/cloud/azure/azure-ai-inference',
                  },
                  {
                    label: 'Azure AI Search',
                    slug: 'integrations/cloud/azure/azure-ai-search',
                  },
                  {
                    label: 'Azure OpenAI',
                    slug: 'integrations/cloud/azure/azure-openai',
                  },
                ],
              },
              {
                label: 'Azure App Configuration',
                slug: 'integrations/cloud/azure/azure-app-configuration',
              },
              {
                label: 'Azure App Service',
                slug: 'integrations/cloud/azure/azure-app-service',
              },
              {
                label: 'Azure Cache for Redis',
                slug: 'integrations/cloud/azure/azure-cache-redis',
              },
              {
                label: 'Azure Container Registry',
                slug: 'integrations/cloud/azure/azure-container-registry',
              },
              {
                label: 'Azure Cosmos DB',
                slug: 'integrations/cloud/azure/azure-cosmos-db',
              },
              {
                label: 'Azure Event Hubs',
                slug: 'integrations/cloud/azure/azure-event-hubs',
              },
              {
                label: 'Azure Functions',
                slug: 'integrations/cloud/azure/azure-functions',
              },
              {
                label: 'Azure Key Vault',
                slug: 'integrations/cloud/azure/azure-key-vault',
              },
              {
                label: 'Azure PostgreSQL',
                slug: 'integrations/cloud/azure/azure-postgresql',
              },
              {
                label: 'Azure Service Bus',
                slug: 'integrations/cloud/azure/azure-service-bus',
              },
              {
                label: 'Azure SignalR Service',
                slug: 'integrations/cloud/azure/azure-signalr',
              },
              {
                label: 'Azure SQL Database',
                slug: 'integrations/cloud/azure/azure-sql-database',
              },
              {
                label: 'Azure Storage',
                collapsed: true,
                items: [
                  {
                    label: 'Azure Storage Blobs',
                    slug: 'integrations/cloud/azure/azure-storage-blobs',
                  },
                  {
                    label: 'Azure Storage Queues',
                    slug: 'integrations/cloud/azure/azure-storage-queues',
                  },
                  {
                    label: 'Azure Storage Tables',
                    slug: 'integrations/cloud/azure/azure-storage-tables',
                  },
                ],
              },
              {
                label: 'Azure Web PubSub',
                slug: 'integrations/cloud/azure/azure-web-pubsub',
              },
              {
                label: 'Azure Container App Jobs',
                slug: 'integrations/cloud/azure/container-app-jobs',
              },
              {
                label: 'User-assigned managed identity',
                slug: 'integrations/cloud/azure/user-assigned-identity',
              },
              {
                label: 'Manage role assignments',
                slug: 'integrations/cloud/azure/role-assignments',
              },
            ],
          },
        ],
      },
      {
        label: 'Caching & state',
        collapsed: true,
        translations: {
          da: 'Caching og tilstand',
          de: 'Caching & Zustand',
          en: 'Caching & state',
          es: 'Caché y estado',
          fr: 'Mise en cache et état',
          hi: 'कैशिंग और स्थिति',
          id: 'Caching & State',
          it: 'Caching e stato',
          ja: 'キャッシングと状態',
          ko: '캐싱 및 상태',
          pt: 'Cache e Estado',
          'pt-BR': 'Cache e Estado',
          'pt-PT': 'Cache e Estado',
          ru: 'Кэширование и состояние',
          tr: 'Önbellekleme ve Durum',
          uk: 'Кешування та стан',
          'zh-CN': '缓存与状态',
        },
        items: [
          {
            label: 'Redis',
            collapsed: true,
            items: [
              {
                label: 'Integration overview',
                slug: 'integrations/caching/redis',
              },
              {
                label: 'Community extensions',
                slug: 'integrations/caching/redis-extensions',
              },
            ],
          },
          {
            label: 'Redis Distributed Cache',
            slug: 'integrations/caching/redis-distributed',
          },
          {
            label: 'Redis Output Cache',
            slug: 'integrations/caching/redis-output',
          },
          { label: 'Valkey', slug: 'integrations/caching/valkey' },
          { label: 'Garnet', slug: 'integrations/caching/garnet' },
        ],
      },
      {
        label: 'Compute & hosting',
        collapsed: true,
        translations: {
          da: 'Compute og hosting',
          de: 'Compute & hosting',
          en: 'Compute & hosting',
          es: 'Computación y alojamiento',
          fr: 'Calcul et hébergement',
          hi: 'कंप्यूट और होस्टिंग',
          id: 'Komputasi & hosting',
          it: 'Calcolo e hosting',
          ja: 'コンピューティングとホスティング',
          ko: '컴퓨팅 및 호스팅',
          pt: 'Computação e hospedagem',
          'pt-BR': 'Computação e hospedagem',
          'pt-PT': 'Computação e alojamento',
          ru: 'Вычисления и хостинг',
          tr: 'Hesaplama ve Barındırma',
          uk: 'Обчислення та хостинг',
          'zh-CN': '计算与托管',
        },
        items: [
          { label: 'Docker', slug: 'integrations/compute/docker' },
          { label: 'Kubernetes', slug: 'integrations/compute/kubernetes' },
        ],
      },
      {
        label: 'Data & databases',
        collapsed: true,
        translations: {
          da: 'Database',
          de: 'Datenbank',
          en: 'Data & databases',
          es: 'Base de datos',
          fr: 'Base de données',
          hi: 'डेटाबेस',
          id: 'Basis Data',
          it: 'Database',
          ja: 'データベース',
          ko: '데이터베이스',
          pt: 'Banco de dados',
          'pt-BR': 'Banco de dados',
          'pt-PT': 'Base de dados',
          ru: 'База данных',
          tr: 'Veritabanı',
          uk: 'База даних',
          'zh-CN': '数据库',
        },
        items: [
          {
            label: 'Elasticsearch',
            slug: 'integrations/databases/elasticsearch',
          },
          {
            label: 'Entity Framework Core',
            items: [
              {
                label: 'Overview',
                slug: 'integrations/databases/efcore/overview',
              },
              {
                label: 'Apply migrations',
                slug: 'integrations/databases/efcore/migrations',
              },
              {
                label: 'Seed data',
                slug: 'integrations/databases/efcore/seed-database',
              },
              {
                label: 'Azure Cosmos DB',
                slug: 'integrations/databases/efcore/azure-cosmos-db',
              },
              {
                label: 'Azure PostgreSQL',
                slug: 'integrations/databases/efcore/azure-postgresql',
              },
              {
                label: 'Azure SQL',
                slug: 'integrations/databases/efcore/azure-sql',
              },
              {
                label: 'MySQL Pomelo',
                slug: 'integrations/databases/efcore/mysql',
              },
              { label: 'Oracle', slug: 'integrations/databases/efcore/oracle' },
              {
                label: 'PostgreSQL',
                slug: 'integrations/databases/efcore/postgresql',
              },
              {
                label: 'SQL Server',
                slug: 'integrations/databases/efcore/sql-server',
              },
            ],
          },
          { label: 'KurrentDB', slug: 'integrations/databases/kurrentdb' },
          { label: 'Meilisearch', slug: 'integrations/databases/meilisearch' },
          { label: 'Milvus', slug: 'integrations/databases/milvus' },
          {
            label: 'MongoDB',
            collapsed: true,
            items: [
              {
                label: 'Integration overview',
                slug: 'integrations/databases/mongodb',
              },
              {
                label: 'Community extensions',
                slug: 'integrations/databases/mongodb-extensions',
              },
            ],
          },
          {
            label: 'MySQL',
            collapsed: true,
            items: [
              {
                label: 'Integration overview',
                slug: 'integrations/databases/mysql',
              },
              {
                label: 'Community extensions',
                slug: 'integrations/databases/mysql-extensions',
              },
            ],
          },
          { label: 'Oracle', slug: 'integrations/databases/oracle' },
          {
            label: 'PostgreSQL',
            collapsed: true,
            items: [
              {
                label: 'Get started',
                slug: 'integrations/databases/postgres/postgres-get-started',
              },
              {
                label: 'Hosting integration (AppHost)',
                slug: 'integrations/databases/postgres/postgres-host',
              },
              {
                label: 'Client integration (Your app)',
                slug: 'integrations/databases/postgres/postgres-client',
              },
              {
                label: 'Community extensions',
                slug: 'integrations/databases/postgres/postgresql-extensions',
              },
            ],
          },
          { label: 'Qdrant', slug: 'integrations/databases/qdrant' },
          { label: 'RavenDB', slug: 'integrations/databases/ravendb' },
          {
            label: 'SQL Server',
            collapsed: true,
            items: [
              {
                label: 'Integration overview',
                slug: 'integrations/databases/sql-server',
              },
              {
                label: 'Community extensions',
                slug: 'integrations/databases/sql-server-extensions',
              },
            ],
          },
          { label: 'SQLite', slug: 'integrations/databases/sqlite' },
          { label: 'SurrealDB', slug: 'integrations/databases/surrealdb' },
        ],
      },
      {
        label: 'Frameworks & runtimes',
        collapsed: true,
        translations: {
          da: 'Frameworks og runtime-miljøer',
          de: 'Frameworks & Laufzeiten',
          en: 'Frameworks & runtimes',
          es: 'Frameworks y entornos de ejecución',
          fr: "Frameworks et environnements d'exécution",
          hi: 'फ्रेमवर्क और रनटाइम',
          id: 'Kerangka & Runtime',
          it: 'Framework e runtime',
          ja: 'フレームワークとランタイム',
          ko: '프레임워크 및 런타임',
          pt: 'Frameworks e Runtimes',
          'pt-BR': 'Frameworks e Runtimes',
          'pt-PT': 'Frameworks e Runtimes',
          ru: 'Фреймворки и среды выполнения',
          tr: 'Çerçeveler ve Çalışma Zamanları',
          uk: 'Фреймворки та середовища виконання',
          'zh-CN': '框架和运行时',
        },
        items: [
          { label: 'Bun apps', slug: 'integrations/frameworks/bun-apps' },
          { label: 'Dapr', slug: 'integrations/frameworks/dapr' },
          { label: 'Deno apps', slug: 'integrations/frameworks/deno-apps' },
          { label: 'Go apps', slug: 'integrations/frameworks/go-apps' },
          { label: 'Java', slug: 'integrations/frameworks/java' },
          { label: '.NET MAUI', slug: 'integrations/frameworks/maui' },
          {
            label: 'Node.js extensions',
            slug: 'integrations/frameworks/nodejs-extensions',
          },
          { label: 'Orleans', slug: 'integrations/frameworks/orleans' },
          { label: 'PowerShell', slug: 'integrations/frameworks/powershell' },
          { label: 'Python', slug: 'integrations/frameworks/python' },
          { label: 'Rust', slug: 'integrations/frameworks/rust' },
        ],
      },
      {
        label: 'Messaging & eventing',
        collapsed: true,
        translations: {
          da: 'Meddelelser',
          de: 'Messaging',
          en: 'Messaging & eventing',
          es: 'Mensajería',
          fr: 'Messagerie',
          hi: 'मैसेजिंग',
          id: 'Pengiriman Pesan',
          it: 'Messaggistica',
          ja: 'メッセージング',
          ko: '메시징',
          pt: 'Mensageria',
          'pt-BR': 'Mensageria',
          'pt-PT': 'Mensageria',
          ru: 'Обмен сообщениями',
          tr: 'Mesajlaşma',
          uk: 'Обмін повідомленнями',
          'zh-CN': '消息传递',
        },
        items: [
          {
            label: 'Apache Kafka',
            slug: 'integrations/messaging/apache-kafka',
          },
          { label: 'LavinMQ', slug: 'integrations/messaging/lavinmq' },
          { label: 'NATS', slug: 'integrations/messaging/nats' },
          { label: 'RabbitMQ', slug: 'integrations/messaging/rabbitmq' },
        ],
      },
      {
        label: 'Security & identity',
        collapsed: true,
        translations: {
          da: 'Sikkerhed og identitet',
          de: 'Sicherheit & Identität',
          en: 'Security & identity',
          es: 'Seguridad e identidad',
          fr: 'Sécurité et identité',
          hi: 'सुरक्षा और पहचान',
          id: 'Keamanan & Identitas',
          it: 'Sicurezza e identità',
          ja: 'セキュリティとアイデンティティ',
          ko: '보안 및 ID',
          pt: 'Segurança e Identidade',
          'pt-BR': 'Segurança e Identidade',
          'pt-PT': 'Segurança e Identidade',
          ru: 'Безопасность и идентификация',
          tr: 'Güvenlik ve Kimlik',
          uk: 'Безпека та ідентичність',
          'zh-CN': '安全与身份',
        },
        items: [{ label: 'Keycloak', slug: 'integrations/security/keycloak' }],
      },
      {
        label: 'Observability & logging',
        collapsed: true,
        translations: {
          da: 'Observerbarhed og logning',
          de: 'Beobachtbarkeit & Protokollierung',
          en: 'Observability & logging',
          es: 'Observabilidad y registro',
          fr: 'Observabilité et journalisation',
          hi: 'पर्यवेक्षण और लॉगिंग',
          id: 'Observabilitas & Logging',
          it: 'Osservabilità e registrazione',
          ja: '可観測性とログ記録',
          ko: '관측 가능성 및 로깅',
          pt: 'Observabilidade e Registro',
          'pt-BR': 'Observabilidade e Registro',
          'pt-PT': 'Observabilidade e Registo',
          ru: 'Наблюдаемость и ведение журналов',
          tr: 'Gözlemlenebilirlik ve Günlük Kaydı',
          uk: 'Спостережуваність та ведення журналів',
          'zh-CN': '可观察性与日志记录',
        },
        items: [{ label: 'Seq', slug: 'integrations/observability/seq' }],
      },
      {
        label: 'Reverse proxies & APIs',
        collapsed: true,
        translations: {
          da: "Reverse proxies & API'er",
          de: 'Reverse Proxies & APIs',
          en: 'Reverse proxies & APIs',
          es: 'Reverse proxies y APIs',
          fr: 'Reverse proxies et APIs',
          hi: 'रिवर्स प्रॉक्सी और एपीआई',
          id: 'Reverse Proxies & API',
          it: 'Reverse proxy e API',
          ja: 'リバースプロキシとAPI',
          ko: '리버스 프록시 및 API',
          pt: 'Reverse Proxies e APIs',
          'pt-BR': 'Reverse Proxies e APIs',
          'pt-PT': 'Reverse Proxies e APIs',
          ru: 'Обратные прокси и API',
          tr: "Ters Proxyler ve API'ler",
          uk: 'Зворотні проксі та API',
          'zh-CN': '反向代理和API',
        },
        items: [
          {
            label: 'YARP (Yet Another Reverse Proxy)',
            slug: 'integrations/reverse-proxies/yarp',
          },
        ],
      },
      {
        label: 'Dev tools & extensions',
        collapsed: true,
        translations: {
          da: 'Dev-værktøjer og udvidelser',
          de: 'Dev-Tools & Erweiterungen',
          en: 'Dev tools & extensions',
          es: 'Herramientas de desarrollo y extensiones',
          fr: 'Outils de développement et extensions',
          hi: 'डेव टूल्स और एक्सटेंशन',
          id: 'Alat & Ekstensi Dev',
          it: 'Strumenti di sviluppo ed estensioni',
          ja: '開発ツールと拡張機能',
          ko: '개발 도구 및 확장 프로그램',
          pt: 'Ferramentas e Extensões de Desenvolvimento',
          'pt-BR': 'Ferramentas e Extensões de Desenvolvimento',
          'pt-PT': 'Ferramentas e Extensões de Desenvolvimento',
          ru: 'Инструменты разработчика и расширения',
          tr: 'Geliştirici Araçları ve Uzantılar',
          uk: 'Інструменти розробника та розширення',
          'zh-CN': '开发工具和扩展',
        },
        items: [
          { label: 'Data API Builder', slug: 'integrations/devtools/dab' },
          { label: 'Dev Tunnels', slug: 'integrations/devtools/dev-tunnels' },
          { label: 'flagd', slug: 'integrations/devtools/flagd' },
          { label: 'goff', slug: 'integrations/devtools/goff' },
          { label: 'k6', slug: 'integrations/devtools/k6' },
          { label: 'MailPit', slug: 'integrations/devtools/mailpit' },
          {
            label: 'SQL Database Projects',
            slug: 'integrations/devtools/sql-projects',
          },
        ],
      },
    ],
  },
  {
    label: {
      en: 'Dashboard',
      es: 'Panel',
      fr: 'Tableau de bord',
      de: 'Dashboard',
      it: 'Dashboard',
      pt: 'Painel',
      ru: 'Панель управления',
      'zh-CN': '仪表板',
      da: 'Dashboard',
      hi: 'डैशबोर्ड',
      id: 'Dasbor',
      ja: 'ダッシュボード',
      ko: '대시보드',
      'pt-BR': 'Painel',
      'pt-PT': 'Painel',
      tr: 'Gösterge Paneli',
      uk: 'Панель керування',
    },
    link: '/dashboard/overview',
    icon: 'seti:happenings',
    items: [
      {
        label: 'Overview',
        translations: {
          da: 'Oversigt',
          de: 'Übersicht',
          en: 'Overview',
          es: 'Descripción general',
          fr: "Vue d'ensemble",
          hi: 'अवलोकन',
          id: 'Ikhtisar',
          it: 'Panoramica',
          ja: '概要',
          ko: '개요',
          pt: 'Visão geral',
          'pt-BR': 'Visão geral',
          'pt-PT': 'Visão geral',
          ru: 'Обзор',
          tr: 'Genel Bakış',
          uk: 'Огляд',
          'zh-CN': '概述',
        },
        slug: 'dashboard/overview',
      },
      {
        label: 'Explore features',
        translations: {
          da: 'Udforsk funktioner',
          de: 'Funktionen erkunden',
          en: 'Explore features',
          es: 'Explorar funciones',
          fr: 'Explorer les fonctionnalités',
          hi: 'विशेषताएँ एक्सप्लोर करें',
          id: 'Jelajahi fitur',
          it: 'Esplora funzionalità',
          ja: '機能を探る',
          ko: '기능 탐색',
          pt: 'Explorar recursos',
          'pt-BR': 'Explorar recursos',
          'pt-PT': 'Explorar recursos',
          ru: 'Изучение функций',
          tr: 'Özellikleri keşfet',
          uk: 'Дослідити функції',
          'zh-CN': '探索功能',
        },
        slug: 'dashboard/explore',
      },
      {
        label: 'GitHub Copilot',
        slug: 'dashboard/copilot',
      },
      {
        label: 'Aspire MCP server',
        translations: {
          da: 'Aspire MCP-server',
          de: 'Aspire MCP-Server',
          en: 'Aspire MCP server',
          es: 'Servidor Aspire MCP',
          fr: 'Serveur Aspire MCP',
          hi: 'Aspire MCP सर्वर',
          id: 'Server Aspire MCP',
          it: 'Server Aspire MCP',
          ja: 'Aspire MCPサーバー',
          ko: 'Aspire MCP 서버',
          pt: 'Servidor Aspire MCP',
          'pt-BR': 'Servidor Aspire MCP',
          'pt-PT': 'Servidor Aspire MCP',
          ru: 'Сервер Aspire MCP',
          tr: 'Aspire MCP sunucusu',
          uk: 'Сервер Aspire MCP',
          'zh-CN': 'Aspire MCP 服务器',
        },
        slug: 'dashboard/mcp-server',
      },
      {
        label: 'Standalone mode',
        translations: {
          da: 'Selvstændig tilstand',
          de: 'Eigenständiger Modus',
          en: 'Standalone mode',
          es: 'Modo independiente',
          fr: 'Mode autonome',
          hi: 'स्टैंडअलोन मोड',
          id: 'Mode mandiri',
          it: 'Modalità autonoma',
          ja: 'スタンドアロンモード',
          ko: '독립 실행 모드',
          pt: 'Modo autônomo',
          'pt-BR': 'Modo autônomo',
          'pt-PT': 'Modo autónomo',
          ru: 'Автономный режим',
          tr: 'Bağımsız mod',
          uk: 'Автономний режим',
          'zh-CN': '独立模式',
        },
        items: [
          { label: 'Overview', slug: 'dashboard/standalone' },
          {
            label: 'Python apps',
            slug: 'dashboard/standalone-for-python',
          },
          {
            label: 'Node.js apps',
            slug: 'dashboard/standalone-for-nodejs',
          },
        ],
      },
      {
        label: 'Configuration',
        translations: {
          da: 'Konfiguration',
          de: 'Konfiguration',
          en: 'Configuration',
          es: 'Configuración',
          fr: 'Configuration',
          hi: 'कॉन्फ़िगरेशन',
          id: 'Konfigurasi',
          it: 'Configurazione',
          ja: '構成',
          ko: '구성',
          pt: 'Configuração',
          'pt-BR': 'Configuração',
          'pt-PT': 'Configuração',
          ru: 'Конфигурация',
          tr: 'Yapılandırma',
          uk: 'Конфігурація',
          'zh-CN': '配置',
        },
        slug: 'dashboard/configuration',
      },
      {
        label: 'Security considerations',
        translations: {
          da: 'Sikkerhedsovervejelser',
          de: 'Sicherheitsüberlegungen',
          en: 'Security considerations',
          es: 'Consideraciones de seguridad',
          fr: 'Considérations de sécurité',
          hi: 'सुरक्षा संबंधी विचार',
          id: 'Pertimbangan keamanan',
          it: 'Considerazioni sulla sicurezza',
          ja: 'セキュリティに関する考慮事項',
          ko: '보안 고려 사항',
          pt: 'Considerações de segurança',
          'pt-BR': 'Considerações de segurança',
          'pt-PT': 'Considerações de segurança',
          ru: 'Соображения безопасности',
          tr: 'Güvenlik değerlendirmeleri',
          uk: 'Міркування щодо безпеки',
          'zh-CN': '安全注意事项',
        },
        slug: 'dashboard/security-considerations',
      },
      {
        label: 'Enable browser telemetry',
        translations: {
          da: 'Aktivér browsertelemetri',
          de: 'Browser-Telemetrie aktivieren',
          en: 'Enable browser telemetry',
          es: 'Habilitar telemetría del navegador',
          fr: 'Activer la télémétrie du navigateur',
          hi: 'ब्राउज़र टेलीमेट्री सक्षम करें',
          id: 'Aktifkan telemetri browser',
          it: 'Abilita telemetria del browser',
          ja: 'ブラウザのテレメトリを有効にする',
          ko: '브라우저 원격 분석 활성화',
          pt: 'Ativar telemetria do navegador',
          'pt-BR': 'Ativar telemetria do navegador',
          'pt-PT': 'Ativar telemetria do navegador',
          ru: 'Включить телеметрию браузера',
          tr: 'Tarayıcı telemetrisi etkinleştirme',
          uk: 'Увімкнути телеметрію браузера',
          'zh-CN': '启用浏览器遥测',
        },
        slug: 'dashboard/enable-browser-telemetry',
      },
      {
        label: 'Microsoft telemetry',
        translations: {
          da: 'Microsoft telemetri',
          de: 'Microsoft-Telemetrie',
          en: 'Microsoft telemetry',
          es: 'Telemetría de Microsoft',
          fr: 'Télémétrie Microsoft',
          hi: 'Microsoft टेलीमेट्री',
          id: 'Telemetri Microsoft',
          it: 'Telemetria Microsoft',
          ja: 'Microsoft テレメトリ',
          ko: 'Microsoft 원격 분석',
          pt: 'Telemetria da Microsoft',
          'pt-BR': 'Telemetria da Microsoft',
          'pt-PT': 'Telemetria da Microsoft',
          ru: 'Телеметрия Microsoft',
          tr: 'Microsoft telemetrisi',
          uk: 'Телеметрія Microsoft',
          'zh-CN': 'Microsoft 遥测',
        },
        slug: 'dashboard/microsoft-collected-dashboard-telemetry',
      },
    ],
  },
  {
    label: {
      en: 'CLI Reference',
      es: 'Referencia de CLI',
      fr: 'Référence CLI',
      de: 'CLI-Referenz',
      it: 'Riferimento CLI',
      pt: 'Referência de CLI',
      ru: 'Справочник CLI',
      'zh-CN': 'CLI 参考',
      da: 'CLI-reference',
      hi: 'CLI संदर्भ',
      id: 'Referensi CLI',
      ja: 'CLI リファレンス',
      ko: 'CLI 참고서',
      'pt-BR': 'Referência de CLI',
      'pt-PT': 'Referência de CLI',
      tr: 'CLI Referansı',
      uk: 'CLI Довідник',
    },
    link: '/reference/cli/overview',
    icon: 'forward-slash',
    items: [
      {
        label: 'Overview',
        translations: {
          da: 'Oversigt',
          de: 'Übersicht',
          en: 'Overview',
          es: 'Descripción general',
          fr: "Vue d'ensemble",
          hi: 'अवलोकन',
          id: 'Ikhtisar',
          it: 'Panoramica',
          ja: '概要',
          ko: '개요',
          pt: 'Visão geral',
          'pt-BR': 'Visão geral',
          'pt-PT': 'Visão geral',
          ru: 'Обзор',
          tr: 'Genel Bakış',
          uk: 'Огляд',
          'zh-CN': '概述',
        },
        slug: 'reference/cli/overview',
      },
      {
        label: 'Install script',
        translations: {
          da: 'Installationsscript',
          de: 'Installationsskript',
          en: 'Install script',
          es: 'Script de instalación',
          fr: "Script d'installation",
          hi: 'इंस्टॉलेशन स्क्रिप्ट',
          id: 'Skrip Instalasi',
          it: 'Script di installazione',
          ja: 'インストールスクリプト',
          ko: '설치 스크립트',
          pt: 'Script de instalação',
          'pt-BR': 'Script de instalação',
          'pt-PT': 'Script de instalação',
          ru: 'Скрипт установки',
          tr: 'Kurulum Betiği',
          uk: 'Скрипт установки',
          'zh-CN': '安装脚本',
        },
        slug: 'reference/cli/install-script',
      },
      {
        label: 'Configuration',
        translations: {
          da: 'Konfiguration',
          de: 'Konfiguration',
          en: 'Configuration',
          es: 'Configuración',
          fr: 'Configuration',
          hi: 'कॉन्फ़िगरेशन',
          id: 'Konfigurasi',
          it: 'Configurazione',
          ja: '構成',
          ko: '구성',
          pt: 'Configuração',
          'pt-BR': 'Configuração',
          'pt-PT': 'Configuração',
          ru: 'Конфигурация',
          tr: 'Yapılandırma',
          uk: 'Конфігурація',
          'zh-CN': '配置',
        },
        slug: 'reference/cli/configuration',
      },
      {
        label: 'Commands',
        translations: {
          da: 'Kommandoer',
          de: 'Befehle',
          en: 'Commands',
          es: 'Comandos',
          fr: 'Commandes',
          hi: 'कमांड',
          id: 'Perintah',
          it: 'Comandi',
          ja: 'コマンド',
          ko: '명령어',
          pt: 'Comandos',
          'pt-BR': 'Comandos',
          'pt-PT': 'Comandos',
          ru: 'Команды',
          tr: 'Komutlar',
          uk: 'Команди',
          'zh-CN': '命令',
        },
        items: [
          { label: 'aspire', slug: 'reference/cli/commands/aspire' },
          { label: 'aspire add', slug: 'reference/cli/commands/aspire-add' },
          {
            label: 'aspire cache',
            collapsed: true,
            items: [
              {
                label: 'aspire cache',
                slug: 'reference/cli/commands/aspire-cache',
              },
              {
                label: 'aspire cache clear',
                slug: 'reference/cli/commands/aspire-cache-clear',
              },
            ],
          },
          {
            label: 'aspire config',
            collapsed: true,
            items: [
              {
                label: 'aspire config',
                slug: 'reference/cli/commands/aspire-config',
              },
              {
                label: 'aspire config list',
                slug: 'reference/cli/commands/aspire-config-list',
              },
              {
                label: 'aspire config get',
                slug: 'reference/cli/commands/aspire-config-get',
              },
              {
                label: 'aspire config set',
                slug: 'reference/cli/commands/aspire-config-set',
              },
              {
                label: 'aspire config delete',
                slug: 'reference/cli/commands/aspire-config-delete',
              },
            ],
          },
          {
            label: 'aspire deploy',
            slug: 'reference/cli/commands/aspire-deploy',
          },
          { label: 'aspire do', slug: 'reference/cli/commands/aspire-do' },
          { label: 'aspire exec', slug: 'reference/cli/commands/aspire-exec' },
          { label: 'aspire init', slug: 'reference/cli/commands/aspire-init' },
          { label: 'aspire new', slug: 'reference/cli/commands/aspire-new' },
          {
            label: 'aspire publish',
            slug: 'reference/cli/commands/aspire-publish',
          },
          { label: 'aspire run', slug: 'reference/cli/commands/aspire-run' },
          {
            label: 'aspire update',
            slug: 'reference/cli/commands/aspire-update',
          },
        ],
      },
    ],
  },
  // {
  //     label: 'API Reference',
  //     id: 'reference-api',
  //     link: '/api',
  //     icon: 'document',
  //     items: [
  //         {
  //             label: 'API Reference',
  //             collapsed: false,
  //             autogenerate: { directory: '/reference/api', collapsed: true }
  //         },
  //     ]
  // },
  {
    label: {
      en: 'Community',
      es: 'Comunidad',
      fr: 'Communauté',
      de: 'Gemeinschaft',
      it: 'Comunità',
      pt: 'Comunidade',
      ru: 'Сообщество',
      'zh-CN': '社区',
      da: 'Fællesskab',
      hi: 'समुदाय',
      id: 'Komunitas',
      ja: 'コミュニティ',
      ko: '커뮤니티',
      'pt-BR': 'Comunidade',
      'pt-PT': 'Comunidade',
      tr: 'Topluluk',
      uk: 'Спільнота',
    },
    link: '/community/contributors',
    icon: 'heart',
    items: [
      {
        label: 'Contributors',
        translations: {
          da: 'Bidragydere',
          de: 'Mitwirkende',
          en: 'Contributors',
          es: 'Colaboradores',
          fr: 'Contributeurs',
          hi: 'योगदानकर्ता',
          id: 'Kontributor',
          it: 'Collaboratori',
          ja: 'コントリビューター',
          ko: '기여자',
          pt: 'Contribuidores',
          'pt-BR': 'Contribuidores',
          'pt-PT': 'Contribuidores',
          ru: 'Участники',
          tr: 'Katkıda Bulunanlar',
          uk: 'Учасники',
          'zh-CN': '贡献者',
        },
        items: [
          {
            label: 'Contributor overview',
            translations: {
              da: 'Oversigt over bidragydere',
              de: 'Übersicht der Mitwirkenden',
              en: 'Contributor overview',
              es: 'Descripción general del colaborador',
              fr: 'Aperçu des contributeurs',
              hi: 'योगदानकर्ता अवलोकन',
              id: 'Ikhtisar kontributor',
              it: 'Panoramica dei collaboratori',
              ja: 'コントリビューターの概要',
              ko: '기여자 개요',
              pt: 'Visão geral do contribuinte',
              'pt-BR': 'Visão geral do contribuinte',
              'pt-PT': 'Visão geral do contribuinte',
              ru: 'Обзор участников',
              tr: 'Katkıda Bulunanlar Genel Bakışı',
              uk: 'Огляд учасників',
              'zh-CN': '贡献者概述',
            },
            slug: 'community/contributors',
          },
          {
            label: 'Contributor guide',
            translations: {
              da: 'Bidragydervejledning',
              de: 'Mitwirkenden-Leitfaden',
              en: 'Contributor guide',
              es: 'Guía del colaborador',
              fr: 'Guide du contributeur',
              hi: 'योगदानकर्ता गाइड',
              id: 'Panduan kontributor',
              it: 'Guida per i collaboratori',
              ja: 'コントリビューターガイド',
              ko: '기여자 가이드',
              pt: 'Guia do contribuinte',
              'pt-BR': 'Guia do contribuinte',
              'pt-PT': 'Guia do contribuinte',
              ru: 'Руководство для участников',
              tr: 'Katkıda Bulunanlar Kılavuzu',
              uk: 'Посібник для учасників',
              'zh-CN': '贡献者指南',
            },
            slug: 'community/contributor-guide',
          },
        ],
      },
      {
        label: 'BlueSky',
        slug: 'community/posts',
        badge: {
          text: '#aspire',
          variant: 'note',
        },
      },
      {
        label: 'Videos',
        translations: {
          da: 'Videoer',
          de: 'Videos',
          en: 'Videos',
          es: 'Videos',
          fr: 'Vidéos',
          hi: 'वीडियो',
          id: 'Video',
          it: 'Video',
          ja: '動画',
          ko: '비디오',
          pt: 'Vídeos',
          'pt-BR': 'Vídeos',
          'pt-PT': 'Vídeos',
          ru: 'Видео',
          tr: 'Videolar',
          uk: 'Відео',
          'zh-CN': '视频',
        },
        slug: 'community/videos',
      },
    ],
  },
  {
    label: {
      en: 'Diagnostics',
      es: 'Diagnósticos',
      fr: 'Diagnostics',
      de: 'Diagnose',
      it: 'Diagnostica',
      pt: 'Diagnósticos',
      ru: 'Диагностика',
      'zh-CN': '诊断',
      da: 'Diagnostik',
      hi: 'निदान',
      id: 'Diagnostik',
      ja: '診断',
      ko: '진단',
      'pt-BR': 'Diagnósticos',
      'pt-PT': 'Diagnósticos',
      tr: 'Tanılama',
      uk: 'Діагностика',
    },
    link: '/diagnostics/overview/',
    icon: 'warning',
    items: [
      { label: 'Overview', link: '/diagnostics/overview' },
      {
        label: 'Warnings',
        items: [
          { label: 'ASPIRE001', link: '/diagnostics/aspire001' },
          { label: 'ASPIRE002', link: '/diagnostics/aspire002' },
          { label: 'ASPIRE003', link: '/diagnostics/aspire003' },
          { label: 'ASPIRE004', link: '/diagnostics/aspire004' },
        ],
      },
      {
        label: 'Errors',
        items: [
          { label: 'ASPIRE006', link: '/diagnostics/aspire006' },
          { label: 'ASPIRE007', link: '/diagnostics/aspire007' },
          { label: 'ASPIRE008', link: '/diagnostics/aspire008' },
          {
            label: 'ASPIREACADOMAIN001',
            link: '/diagnostics/aspireacadomains001',
          },
          { label: 'ASPIRECOMPUTE001', link: '/diagnostics/aspirecompute001' },
          {
            label: 'ASPIRECOSMOSDB001',
            link: '/diagnostics/aspirecosmosdb001',
          },
          {
            label: 'ASPIREHOSTINGPYTHON001',
            link: '/diagnostics/aspirehostingpython001',
          },
          {
            label: 'ASPIREPIPELINES001',
            link: '/diagnostics/aspirepipelines001',
          },
          {
            label: 'ASPIREPIPELINES002',
            link: '/diagnostics/aspirepipelines002',
          },
          {
            label: 'ASPIREPIPELINES003',
            link: '/diagnostics/aspirepipelines003',
          },
          {
            label: 'ASPIREPROXYENDPOINTS001',
            link: '/diagnostics/aspireproxyendpoints001',
          },
          {
            label: 'ASPIREPUBLISHERS001',
            link: '/diagnostics/aspirepublishers001',
          },
          { label: 'ASPIREAZURE001', link: '/diagnostics/aspireazure001' },
          { label: 'ASPIREAZURE002', link: '/diagnostics/aspireazure002' },
        ],
      },
    ],
  },
];
